package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

exports_files(
    [
        "build.sh",
        "checks.rb",
    ],
    visibility = ["//website:__pkg__"],
)
