# Owners left BUILT in original RC bucket 11 invocation
# b2d70700-93c0-4de3-aa76-8d062fa2e3cc at source 910bc18b8c.
//test/syscalls:close_range_test_runsc_kvm_rc_kvm
//test/syscalls:dup_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:fallocate_test_runsc_ptrace_rc_kvm
//test/syscalls:fault_test_runsc_ptrace_rc_kvm
//test/syscalls:fifo_test_native_rc_kvm
//test/syscalls:fifo_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:fuse_test_runsc_systrap_fuse_rc_kvm
//test/syscalls:getdents_test_runsc_kvm_rc_kvm
//test/syscalls:kcov_test_runsc_ptrace_rc_kvm
//test/syscalls:link_test_runsc_systrap_shared_rc_kvm
//test/syscalls:mempolicy_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:mkdir_test_native_rc_kvm
//test/syscalls:mkdir_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:mknod_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:mknod_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:mmap_eternal_test_runsc_kvm_rc_kvm
//test/syscalls:network_namespace_test_runsc_systrap_hostnet_rc_kvm
//test/syscalls:packet_mmap_test_runsc_systrap_shared_rc_kvm
//test/syscalls:partial_bad_buffer_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:pidfd_test_runsc_kvm_rc_kvm
//test/syscalls:pipe_external_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:poll_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:proc_net_test_runsc_systrap_shared_rc_kvm
//test/syscalls:process_vm_read_write_test_native_rc_kvm
//test/syscalls:pty_root_test_native_rc_kvm
//test/syscalls:pty_root_test_runsc_systrap_shared_rc_kvm
//test/syscalls:pwritev2_test_runsc_ptrace_rc_kvm
//test/syscalls:readv_socket_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:rename_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:rlimits_test_native_rc_kvm
//test/syscalls:setgid_test_runsc_systrap_overlay_rc_kvm
//test/syscalls:sigaction_test_runsc_kvm_rc_kvm
//test/syscalls:socket_abstract_test_native_rc_kvm
//test/syscalls:socket_abstract_test_runsc_ptrace_rc_kvm
//test/syscalls:socket_ip_tcp_generic_loopback_test_native_rc_kvm
//test/syscalls:socket_ip_tcp_loopback_test_runsc_systrap_shared_rc_kvm
//test/syscalls:socket_ip_udp_loopback_non_blocking_test_runsc_systrap_hostnet_rc_kvm
//test/syscalls:socket_ip_udp_loopback_test_runsc_kvm_rc_kvm
//test/syscalls:socket_ip_udp_loopback_test_runsc_systrap_shared_rc_kvm
//test/syscalls:socket_ipv4_udp_unbound_loopback_nogotsan_test_runsc_ptrace_rc_kvm
//test/syscalls:socket_ipv4_udp_unbound_loopback_nogotsan_test_runsc_systrap_hostnet_rc_kvm
//test/syscalls:socket_ipv6_udp_unbound_external_networking_test_native_rc_kvm
//test/syscalls:socket_ipv6_udp_unbound_external_networking_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:socket_ipv6_unbound_test_runsc_systrap_hostnet_rc_kvm
//test/syscalls:socket_netlink_netfilter_test_native_rc_kvm
//test/syscalls:socket_netlink_uevent_test_runsc_systrap_shared_rc_kvm
//test/syscalls:socket_stream_blocking_local_test_runsc_kvm_rc_kvm
//test/syscalls:socket_stream_blocking_tcp_test_runsc_systrap_shared_rc_kvm
//test/syscalls:socket_unix_dgram_local_test_native_rc_kvm
//test/syscalls:socket_unix_dgram_non_blocking_test_runsc_systrap_directfs_rc_kvm
//test/syscalls:socket_unix_stream_test_runsc_systrap_shared_rc_kvm
//test/syscalls:socket_unix_unbound_dgram_test_native_rc_kvm
//test/syscalls:statfs_test_runsc_kvm_rc_kvm
//test/syscalls:tuntap_hostinet_test_runsc_kvm_rc_kvm
//test/syscalls:unlink_test_runsc_systrap_overlay_rc_kvm
