load("//tools:defs.bzl", "go_library")

package(
    default_applicable_licenses = ["//:license"],
    licenses = ["notice"],
)

go_library(
    name = "shadow",
    srcs = ["types.go"],
    visibility = ["//pkg/state/tests:__pkg__"],
)
