load("//tools:defs.bzl", "bzl_library")

package(default_applicable_licenses = ["//:license"])

bzl_library(
    name = "repositories_bzl",
    srcs = ["repositories.bzl"],
    visibility = ["//visibility:public"],
)
