FROM ubuntu:jammy
RUN apt-get update && apt-get install -y \
  autoconf \
  automake \
  bison \
  build-essential \
  curl \
  libsqlite3-dev \
  libtool \
  libxml2-dev \
  patch \
  pkg-config \
  re2c

WORKDIR /root
ARG VERSION=8.5.11
RUN curl --fail --location -o php-${VERSION}.tar.gz https://www.php.net/distributions/php-${VERSION}.tar.gz
RUN echo "338630ba9450f0b938bef8d740162c61c33bf64a1b421c6333c01df8a9fdb0ab  php-${VERSION}.tar.gz" | sha256sum --check -
RUN tar -zxf php-${VERSION}.tar.gz

WORKDIR /root/php-${VERSION}
COPY extensions.patch /tmp/extensions.patch
RUN patch -p1 --fuzz=0 --no-backup-if-mismatch < /tmp/extensions.patch \
  && rm -f /tmp/extensions.patch

RUN ./configure
RUN make -j $(nproc)
