# Generated by //tools/nvidia_driver_differ/sources:update. Do not edit.
"""Pinned public sources; None records a missing public tag."""

DRIVER_SOURCES = {
    "535.129.03": "@nvidia_driver_535_129_03",
    "535.183.06": "@nvidia_driver_535_183_06",
    "535.247.01": "@nvidia_driver_535_247_01",
    "535.261.03": "@nvidia_driver_535_261_03",
    "535.274.02": "@nvidia_driver_535_274_02",
    "535.288.01": "@nvidia_driver_535_288_01",
    "535.309.01": "@nvidia_driver_535_309_01",
    "550.90.12": "@nvidia_driver_550_90_12",
    "570.124.06": "@nvidia_driver_570_124_06",
    "570.133.20": "@nvidia_driver_570_133_20",
    "570.172.08": "@nvidia_driver_570_172_08",
    "570.195.03": "@nvidia_driver_570_195_03",
    "580.65.06": "@nvidia_driver_580_65_06",
    "580.105.08": "@nvidia_driver_580_105_08",
    "580.126.09": "@nvidia_driver_580_126_09",
    "580.126.20": "@nvidia_driver_580_126_20",
    "580.159.03": "@nvidia_driver_580_159_03",
    "580.159.04": "@nvidia_driver_580_159_04",
    "580.167.08": "@nvidia_driver_580_167_08",
    "580.173.02": "@nvidia_driver_580_173_02",
    "580.173.10": None,  # No matching tag in the successful public Git advertisement.
    "580.178.04": "@nvidia_driver_580_178_04",
    "590.48.01": "@nvidia_driver_590_48_01",
    "610.57.04": "@nvidia_driver_610_57_04",
    "615.15.00": None,  # No matching tag in the successful public Git advertisement.
    "615.62.00": None,  # No matching tag in the successful public Git advertisement.
    "615.71.09": "@nvidia_driver_615_71_09",
    "620.06.00": None,  # No matching tag in the successful public Git advertisement.
    "620.30.00": None,  # No matching tag in the successful public Git advertisement.
}
