// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Binary update pins public source archives for nvproxy's supported drivers.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"gvisor.dev/gvisor/pkg/sentry/devices/nvproxy"
	"gvisor.dev/gvisor/tools/nvidia_driver_differ/parser"
)

const (
	beginMarker = "# BEGIN generated NVIDIA driver sources"
	endMarker   = "# END generated NVIDIA driver sources"
)

// sourcePin records an immutable source archive. An empty commit means the
// tag advertisement succeeded but contained no matching version.
type sourcePin struct {
	version string
	commit  string
	sha256  string
}

func (p sourcePin) repoName() string {
	return "nvidia_driver_" + strings.ReplaceAll(p.version, ".", "_")
}

func archiveURL(commit string) string {
	return strings.TrimSuffix(parser.GitRepoURL, ".git") + "/archive/" + commit + ".tar.gz"
}

func fetch(ctx context.Context, client *http.Client, url string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "gvisor-nvidia-source-updater")
	return client.Do(req)
}

// tagCommits resolves lightweight and annotated tags from a successful complete
// git ls-remote --tags advertisement. Peeled refs take precedence regardless of
// their order; a malformed advertisement must not turn into missing coverage.
func tagCommits(output []byte) (map[string]string, error) {
	refs := make(map[string]string)
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 || !strings.HasPrefix(fields[1], "refs/tags/") {
			return nil, fmt.Errorf("invalid tag advertisement line %q", line)
		}
		sha, err := hex.DecodeString(fields[0])
		if err != nil || len(sha) != 20 {
			return nil, fmt.Errorf("invalid tag object ID %q", fields[0])
		}
		if _, ok := refs[fields[1]]; ok {
			return nil, fmt.Errorf("duplicate advertised ref %q", fields[1])
		}
		refs[fields[1]] = fields[0]
	}
	commits := make(map[string]string)
	for ref, sha := range refs {
		if base, peeled := strings.CutSuffix(ref, "^{}"); peeled {
			if _, ok := refs[base]; !ok {
				return nil, fmt.Errorf("peeled ref %q has no tag", ref)
			}
			continue
		}
		if peeled, ok := refs[ref+"^{}"]; ok {
			sha = peeled
		}
		commits[strings.TrimPrefix(ref, "refs/tags/")] = sha
	}
	return commits, nil
}

func pinSource(ctx context.Context, client *http.Client, version, commit string) (sourcePin, error) {
	pin := sourcePin{version: version, commit: commit}
	if commit == "" {
		return pin, nil
	}
	archive, err := fetch(ctx, client, archiveURL(pin.commit))
	if err != nil {
		return pin, fmt.Errorf("download %s: %w", version, err)
	}
	defer archive.Body.Close()
	if archive.StatusCode != http.StatusOK {
		return pin, fmt.Errorf("download %s: HTTP %s", version, archive.Status)
	}
	hash := sha256.New()
	if _, err := io.Copy(hash, archive.Body); err != nil {
		return pin, fmt.Errorf("hash %s: %w", version, err)
	}
	pin.sha256 = hex.EncodeToString(hash.Sum(nil))
	return pin, nil
}

func render(pins []sourcePin) (string, string) {
	var module, sources strings.Builder
	fmt.Fprintln(&module, beginMarker)
	fmt.Fprintln(&module, "# Generated by //tools/nvidia_driver_differ/sources:update. Do not edit.")
	fmt.Fprintln(&sources, "# Generated by //tools/nvidia_driver_differ/sources:update. Do not edit.")
	fmt.Fprintln(&sources, "\"\"\"Pinned public sources; None records a missing public tag.\"\"\"")
	fmt.Fprintln(&sources, "\nDRIVER_SOURCES = {")
	for _, pin := range pins {
		if pin.commit == "" {
			fmt.Fprintf(&sources, "    %q: None,  # No matching tag in the successful public Git advertisement.\n", pin.version)
			continue
		}
		fmt.Fprintf(&sources, "    %q: %q,\n", pin.version, "@"+pin.repoName())
		fmt.Fprintf(&module, `
http_archive(
    name = %q,
    build_file = "//tools/nvidia_driver_differ:driver_source.BUILD",
    sha256 = %q,
    strip_prefix = %q,
    urls = [%q],
)
`, pin.repoName(), pin.sha256, "open-gpu-kernel-modules-"+pin.commit, archiveURL(pin.commit))
	}
	fmt.Fprintln(&module, endMarker)
	fmt.Fprintln(&sources, "}")
	return module.String(), sources.String()
}

// replacePins changes only the block owned by this generator. Its first run
// appends the block; damaged or repeated delimiters must not hide other content.
func replacePins(module, block string) (string, error) {
	if !strings.Contains(module, beginMarker) && !strings.Contains(module, endMarker) {
		return strings.TrimRight(module, "\n") + "\n\n" + block, nil
	}
	if strings.Count(module, beginMarker) != 1 || strings.Count(module, endMarker) != 1 {
		return "", fmt.Errorf("MODULE.bazel must have exactly one matching NVIDIA source block")
	}
	before, rest, _ := strings.Cut(module, beginMarker)
	_, after, ok := strings.Cut(rest, endMarker)
	if !ok {
		return "", fmt.Errorf("NVIDIA source block ends before it begins")
	}
	return before + strings.TrimSuffix(block, "\n") + after, nil
}

func update(ctx context.Context, workspace string) error {
	modulePath := filepath.Join(workspace, "MODULE.bazel")
	module, err := os.ReadFile(modulePath)
	if err != nil {
		return err
	}
	// Validate the owned block before making network requests or changing files.
	if _, err := replacePins(string(module), ""); err != nil {
		return err
	}
	cmd := exec.CommandContext(ctx, "git", "ls-remote", "--tags", parser.GitRepoURL)
	// Avoid Git discovering the synthetic .git file in Bazel's output tree.
	cmd.Dir = workspace
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	output, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("list public driver tags: %w: %s", err, stderr.String())
	}
	commits, err := tagCommits(output)
	if err != nil {
		return err
	}
	nvproxy.Init()
	client := &http.Client{Timeout: 5 * time.Minute}
	var pins []sourcePin
	for _, version := range nvproxy.SupportedDrivers() {
		pin, err := pinSource(ctx, client, version.String(), commits[version.String()])
		if err != nil {
			return err
		}
		pins = append(pins, pin)
		if pin.commit == "" {
			fmt.Fprintf(os.Stderr, "%s: no public source version\n", version)
		} else {
			fmt.Fprintf(os.Stderr, "%s: %s\n", version, pin.commit)
		}
	}
	block, sources := render(pins)
	updated, err := replacePins(string(module), block)
	if err != nil {
		return err
	}
	if err := os.WriteFile(modulePath, []byte(updated), 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(workspace, "tools/nvidia_driver_differ/driver_sources.bzl"), []byte(sources), 0644)
}

func main() {
	workspace := flag.String("workspace", os.Getenv("BUILD_WORKSPACE_DIRECTORY"), "repository root to update")
	flag.Parse()
	if *workspace == "" || flag.NArg() != 0 {
		flag.Usage()
		os.Exit(1)
	}
	if err := update(context.Background(), *workspace); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
